stages:
  - lint
  - build
  - test

clippy-check:
  stage: lint
  tags:
    - rust-runner
  script: 
    - rustup component add clippy
    - cd NanoVNA-Saver
    - cargo clippy --all-targets --all-features -- -Dwarnings
  
formatter:
  stage: lint
  tags:
    - rust-runner
  script:
    - rustup component add rustfmt
    - cd NanoVNA-Saver
    - cargo fmt --all -- --check

rust-latest:
  stage: build
  tags:
    - rust-runner
  script:
    - cd NanoVNA-Saver
    - cargo build --verbose

test:
  stage: test
  tags:
    - rust-runner
  script:
    - cd NanoVNA-Saver
    - cargo test --verbose
