stages:
  - build
  - test

rust-latest:
  stage: build
  image: rust:latest
  script:
    - cd NanoVNA-Saver
    - cargo build --verbose
    - cargo test --verbose

rust-nightly:
  stage: build
  image: rustlang/rust:nightly
  script:
    - cd NanoVNA-Saver
    - cargo build --verbose
    - cargo test --verbose
  allow_failure: true

test:
  stage: test
  image: rust:latest
  script:
    - cd NanoVNA-Saver
    - cargo test --verbose
