stages:
  - lint
  - build
  - test

clippy-check:
  stage: lint
  image: rust:latest
  script: 
    - rustup component add clippy
    - rustup component add rustfmt
    - cd NanoVNA-Saver
    - cargo fmt --all -- --check
    - cargo clippy --all-targets --all-features -- -Dwarnings

rust-latest:
  stage: build
  image: rust:latest
  script:
    - cd NanoVNA-Saver
    - cargo build --verbose
    - cargo test --verbose

test:
  stage: test
  image: rust:latest
  script:
    - cd NanoVNA-Saver
    - cargo test --verbose
